### ISSUE TITLE
Is this library production ready?

### ISSUE THREAD

**Issue by sidwebworks** [cathykc/bx-stable-infinite-scroll#1]
Hi I am looking to use this for my web app's real time chat. Just wanted  to ask is this stable enough?

**Comment by cathykc** [comment]
I use this package at my company - we're building https://www.dispatch.do/ . As of right now it's actively maintained!

Let me know if you have any questions / trouble using it.

**Comment by sidwebworks** [comment]
Thanks for the quick reply, that's great.

But I am trying to use this with react query's infinite query.

and I did replicate your example but how do I set the scrollable target element? like the element which we want to behave as the scroll container

**Comment by sidwebworks** [comment]
And because my project is a chat app, am I a little confused by the demo example, as if I will be storing many messages in state there are going to be performance issues. So does the component like remove the bottom elements automatically or something so to cut down the performance bottleneck?

**Comment by sidwebworks** [comment]
Okay i got it working with real time chat and react query as well
thanks this was very useful, will try to contribute in your project you got quite a cool collections.

but I found one bug in the scroll component.

When the loading ends the component leaves a `"0"` string in the dom.
due to the whole scroller alignment changes.

Before
![image](https://user-images.githubusercontent.com/58144379/125150433-62291600-e15d-11eb-8a54-89b24488913c.png)

After 
![image](https://user-images.githubusercontent.com/58144379/125150444-70773200-e15d-11eb-8316-c708bc5acc07.png)

**Comment by cathykc** [comment]
Good find - will fix the `0` bug. Glad you got it working!
