### ISSUE TITLE
Long lists causing performance issues, Integration with React-window or React-virtual for windowing long lists

### ISSUE THREAD

**Issue by sidwebworks** [cathykc/bx-stable-infinite-scroll#2]
Hi any ideas how this can be integrated with react-window or react-virtual  for better performance?

**Comment by cathykc** [comment]
I use this with react-window rn! You basically just nest the `<List></List>` component from `react-window` inside `<BxInfiniteScroll></BxInfiniteScroll>`

I can create an example later today.

**Comment by sidwebworks** [comment]
Thanks, Cathy, Sure I will try to do it. But anyways would really appreciate an example sandbox or something for reference.
also wanted to let you know that because it's messages the height will be dynamic so would love to see how u will approach something like this.

**Comment by sidwebworks** [comment]
I tried it with `VariableSizeList` and `AutoSizer` altho it gives me 2 scroll bars, on further inspecting it looks like both components are creating their own scroll bars.

**Comment by sidwebworks** [comment]
![image](https://user-images.githubusercontent.com/58144379/125192220-507e6600-e264-11eb-8c2d-5fc6bf3daf8a.png)
here is how it looks

**Comment by sidwebworks** [comment]
https://codesandbox.io/s/react-chat-simulator-yg114?file=/src/ChatRoom/Room/Room.js

I am trying to integrate it with this example, but really confused on how BxScroll component is going to handle this

**Comment by cathykc** [comment]
Really sorry for the long turn around time! We were focusing on other parts of our product the past couple months. Released a new version `1.1.0` that exposes a `BxInfiniteScrollVirtualized` component that uses `react-virtual`. 

Here's an example of how to use it: https://github.com/cathykc/bx-stable-infinite-scroll/blob/master/examples/src/AppVirtualized.tsx

Will type up more documentation here this week: https://cathykc.github.io/bx-stable-infinite-scroll/virtualized
