### ISSUE TITLE
Add React 17 in peerDependencies

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [cathykc/bx-stable-infinite-scroll#3]
Would it be possible to add React 17 (maybe 18) as peerDependencies?

Thanks!
Taiwo

**Comment by muyiwaoyeniyi** [comment]
@cathykc Any change the deps can be updated? Thanks!

**Comment by cathykc** [comment]
Thanks for flagging!

**Comment by muyiwaoyeniyi** [comment]
My pleasure. And thanks for the gem. I would like to show you our use case if you are interested.

**Comment by cathykc** [comment]
Definitely! Always a pleasure to know how the things we build are being used by the community :)

**Comment by muyiwaoyeniyi** [comment]
Sounds good. I will reach out once the app is a bit more stable. Thanks!!
